Traceback (most recent call last):
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\rosemary yu\miniconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\rosemary yu\miniconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
infile = open('/content/gdrive/MyDrive/CFB_2022/example.bed', 'r')
for line in infile:
    print(line)
infile.close()
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Input [1;32mIn [2][0m, in [0;36m<cell line: 1>[1;34m()[0m
[1;32m----> 1[0m infile [38;5;241m=[39m [38;5;28;43mopen[39;49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43m/content/gdrive/MyDrive/CFB_2022/example.bed[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m
[0;32m      2[0m [38;5;28;01mfor[39;00m line [38;5;129;01min[39;00m infile:
[0;32m      3[0m     [38;5;28mprint[39m(line)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/CFB_2022/example.bed'
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/MyDrive/CFB_2022/example.bed'

